### PR TITLE
adds new method: leek_anomaly

### PR DESCRIPTION
**Pull request by hagg30**
The following pull request is to add new method leek_anomaly that is runner for testing the our pytorch models.

Our methodology is heavily based on https://github.com/shjung13/Standardized-max-logits. So the dependencies are not much different either.

To avoid the argparse error. we tried to disable our args parse code by giving parser meaningless input. Hope it works.

### CODE REVIEW

**Comment by hermannsblum** [comment]
@hagg30 this here looks all good, but the code that you submitted does not yet work as a package:

```
  File "experiments/fishyscapes.py", line 254, in leek_anomaly
    from leek_anomaly import network_wrapper
  File "/pkg/leek_anomaly/network_wrapper.py", line 9, in <module>
    import network
ModuleNotFoundError: No module named 'network'
```
Can you please upload a new version that really works as a `leek_anomaly` package?

**Comment by hagg30** [comment]
@hermannsblum Thank you for reporting the error.

I've done a resubmit new version of my code at fishyscape.com.

I implemented it to work as a normal package in my environment, but if there are any problems, I would appreciate it if you let me know.

**Comment by hagg30** [comment]
Adds new methods to cityscapes_mIoU.py and timing.py

**Comment by hermannsblum** [comment]
done

**Pull request closed without merging**
