### PR TITLE
Anomaly Detection

### PR DESCRIPTION
**Pull request by Shangui-zh**
A pull-request for fishyscapes

### CODE REVIEW

**Comment by hermannsblum** [comment]
@Shangui-zh Please follow the website instructions to submit  your model and let me know if there are any problems.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by Shangui-zh** [comment]
> A new container image was submitted.
I was confused about the validation. The website said "Re-run the validation job in github and check if the validation of the pull-request succeeds.". How can I do the validation job in github and check the validation? What should I do? Thanks

**Comment by Shangui-zh** [comment]
> 

@hermannsblum I have submitted a new one. Are you received？

**Comment by hermannsblum** [comment]
@Shangui-zh Apologies, the validation runner needed an update. It runs now, and you can see where it fails. To trigger re-runs, you simply upload a new image and after that commit a small change to the json file. I will run everything on the cluster once the validation here succeeds.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by Shangui-zh** [comment]
> 
@hermannsblum Now I have passed the test. All I need to do is waiting, right?

**Comment by hermannsblum** [comment]
yes, I will publish the results online once I have them. Thanks for your submission :) I will write here again once everything is online

**Comment by hermannsblum** [comment]
results are online, thanks for your submission :)

**Pull request closed without merging**
