### PR TITLE
PEB-rerun

### PR DESCRIPTION
**Pull request by TonniaGao**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Hey Hermann, I have submitted three versions of our method: Salat (rev2, rev3) and PEB-rerun. Could you test them all on the cluster? Thank you really much!

**Comment by hermannsblum** [comment]
sure, but can you first trigger the validation? If they oom I will try it directly on the cluster, but is saves trouble if there is any error before that

**Comment by TonniaGao** [comment]
Yes, they can cause OOM. Sorry about that. Never mind, I will validate it first.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Hi Hermann, I have finished validating these three versions. PEB-rerun has problem of OOM, and Salat rev2/3 may have problems evaluating IOU due to error in our code. But as the situation is quite urgent, could you run all of these three versions on the cluster and report the currently available result first? Thank you for your hard work. Really appreciate it!

**Comment by TonniaGao** [comment]
Could you run this one as well? Validation fails due to OOM... Thanks!

**Comment by hermannsblum** [comment]
results are online

**Pull request closed without merging**
