### PR TITLE
Update validation_performance.json

### PR DESCRIPTION
**Pull request by xiasong0501**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
sorry for the inconvenience, the cluster has a maintenance break until next week

**Comment by xiasong0501** [comment]
sure, no problem😀

**Comment by xiasong0501** [comment]
Hi, is there any problem with our provided container? 
thanks

**Comment by hermannsblum** [comment]
@xiasongnihao Got the validation runner to run again, but there are errors in your submission. Please fix them, upload a new image, and trigger evaluation runs through tiny changes in the json file.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by xiasong0501** [comment]
@hermannsblum Hi Hermann, a new .simg file is uploaded. Could you help get the validation run again?
Thanks

**Comment by hermannsblum** [comment]
you can just trigger a new validation by pushing a tiny change in the json, eg adding a 0 at the end of one metric

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by xiasong0501** [comment]
@hermannsblum Hi Hermann, may I ask when can I get the test performance in Fishyscape. As it's a bit near the submission deadline of our targeted conference (approximately 72 hours remaining), we really want to get the result as solid proof of our method.
Thanks a lot~

**Comment by hermannsblum** [comment]
results are online

**Comment by xiasong0501** [comment]
received! 
greatly appreciate for your kind help

**Pull request closed without merging**
