### PR TITLE
ADFSE-OE

### PR DESCRIPTION
**Pull request by silviogalesso**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by silviogalesso** [comment]
Submitted a container to evaluate. Thank you for your work!

**Comment by hermannsblum** [comment]
@silviogalesso please retrigger the validation through small changes in the json file. Once the validation succeeds, I can evaluate it on the test set.

**Comment by silviogalesso** [comment]
As far as I could see, after retriggering the contained was executed until it encountered a CUDA out of memory error.

**Comment by hermannsblum** [comment]
@silviogalesso you're right. Results are online, runtime will be added once the job finishes.

**Comment by silviogalesso** [comment]
Hi, are there any rules for submitting other versions of the same method, except for the 7 days waiting time?

**Comment by hermannsblum** [comment]
So far not. We aim for a balance between allowing to make the most use of the benchmark and avoiding overfitting. If we get the impression the 7-day-rule does not work anymore we will change it, but otherwise will help you get as much evaluation as possible.

**Pull request closed without merging**
