### PR TITLE
EAM_r50

### PR DESCRIPTION
**Pull request by shyam671**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@shyam671 there is a validation error with your method

**Comment by shyam671** [comment]
@hermannsblum I can see the EAM image file gives all the desired output also prints the auprc and FPR95. However, it fails the assertion error. So, I am not able to understand what is the need for assertion check in line 122,123? I might be missing something.

**Comment by hermannsblum** [comment]
@shyam671 the eval fails because you expect a higher AP than we get on the validation set, indicating something could be executed wrongly in your container. If you are fine with this, I can still run this container over the benchmark?

**Comment by shyam671** [comment]
@hermannsblum Sure. Please go ahead with the benchmark.

**Comment by hermannsblum** [comment]
first results are online

**Pull request closed without merging**
