### PR TITLE
update val json

### PR DESCRIPTION
**Pull request by TonniaGao**
May I know when will the cluster maintenance complete?

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Dear Hermann,
Hi! I wonder if you could kindly expedite my benchmark process because the results are crucial to my rebuttal which is fast approaching the deadline on Aug 9th. I greatly appreciate your kind understanding!

**Comment by hermannsblum** [comment]
I am sorry, but the ETH GPU cluster is completely shut down for maintainance from August 4 to August 11. I have no idea why they decided to do this during the 3DV submission and NeurIPS rebuttal period.

Nevertheless, I finally got the validation runner to work, and it shows some errors in your submitted image. You need to fix these errors before I can run anything, but I won't be able to run on the test set before August 11.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Thanks for your reply! I have resubmitted a container image but encountered another runtime error. It seems like my software has exceeded the shared memory limit. Is there a workaround to this problem?

**Comment by TonniaGao** [comment]
I guess the problem was due to the num_worker setting of my dataloader, I will upload a new image again to check.

**Comment by hermannsblum** [comment]
Perfect, I was just about to send you a link with the same suggested fix.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Thanks, but I think my model needs 18Gb of vram to run. T_T

**Comment by hermannsblum** [comment]
uups OK I don't have that on the github action runner. I will then just directly run your submission on the GPU cluster once it becomes online and hope that all works. You can see here once our cluster is operational again: https://scicomp.ethz.ch/wiki/System_status

**Comment by TonniaGao** [comment]
No problem. Greatly appreciate your help!

**Comment by hermannsblum** [comment]
results are online

**Comment by TonniaGao** [comment]
Hi Hermann! Could you help anonymize our method on the website for now? Thank you!

**Comment by hermannsblum** [comment]
done, you are now anonymous submission (salat)

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Hi Hermann, I have uploaded a new version our method. Could you kindly help to run it on your cluster? Or should I open another pull request for the new rev? Thanks a lot!

**Comment by hermannsblum** [comment]
please open another pull request, because I use the id of the PR as the database index 😃

**Pull request closed without merging**
