### PR TITLE
add fishyscapes_nls

### PR DESCRIPTION
**Pull request by NazirNayal8**
Greetings, I would like to evaluate a new method. I submitted the full necessary code to the form. Many thanks in advance.

### CODE REVIEW

**Comment by NazirNayal8** [comment]
I have submitted 3 models (3 zip files) that can be run with the code added by this PR, the zipfile names are `nls.zip`, `nl_oe_12k_diversity`, and `nls_oe_30k_diversity`. It is enough to open a single PR for 3 of them right ?

**Comment by hermannsblum** [comment]
Thanks for your submission! We are very packed with submissions coming in right before CVPR deadline, so it will depend a lot on how well your code is already prepared to run on our cluster, but my colleague @jixing96 will be helping you to get results soon!

**Comment by NazirNayal8** [comment]
Greetings, I would like to ask if there are any updates on when I hear about this submission. I have submitted one additional model today and would like to get the results before the CVPR submission deadline. Much Appreciated! Thanks in advance.

**Comment by jiaxux** [comment]
Hi! I am currently processing both your previous submissions and your new model. You will get all the evaluations very soon. I hope this will work for you :blush:.

**Comment by jiaxux** [comment]
Hi! During the evaluation of your code, I can observe some errors regarding dataset registration from the package `detectron2` you used in your submission. Here is an example `AssertionError: Dataset 'ade20k_instance_train' is already registered!`. It seems that during various import sources from your current code structure, some of the imported datasets are registered multiple times. I am trying to finalize the evaluations asap, so it would be great if you could look at what might introduce this error (or I might miss something while executing your code). Thanks.

**Comment by NazirNayal8** [comment]
Looking into it immediately

**Comment by NazirNayal8** [comment]
I fixed the issue, shall I resubmit the code through the form ?

**Comment by NazirNayal8** [comment]
perhaps to save time, I can share the package that I modified and you can replace it in the submissions, does that sounds reasonable ?

**Comment by jiaxux** [comment]
Sure you can share the modified package in a zip file with me (e.g., via Google Drive or whatever is convenient for you). Also would be great if you could roughly mention where/what did you modify. This will save some of my time as I have already done multiple internal modifications on your submitted codebase. Thanks in advance.

**Comment by NazirNayal8** [comment]
I simply removed unnecessary files that are causing `__init__.py` to be called twice and hence register some modules more than once. I removed them from the `mask2former` package, you may download it from here: 

https://drive.google.com/file/d/1OrDVH-tRzZcEa01MNU3SObrEAkdIhMkR/view?usp=share_link

I tested it by importing it again and making sure the errors disappeared. The files I removed are as follows:

* `mask2former.modeling.backbone.mynn.py`
* `mask2former.modeling.backbone.wideresnet38.py`
* `mask2former.data/*`

Thanks a lot for your patience.

**Comment by jiaxux** [comment]
Hi! Can I ask if the environment versions you provided in your submission were already validated on a GPU?  Now I am using exactly the same installation requirements you listed. However, during inference noticed some errors during the model inference I can always observe `error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device`, which I think should be some version compatibility issues. So I was wondering if you have encountered a similar problem before. I am using an Nvidia RTX 6000 with cuda 11.1.1 and cudnn 8.1.0.77. Thanks.

**Comment by NazirNayal8** [comment]
Yes, I validated the settings on an RTX 3090 with cuda 11.1 and cudnn. There is a step in the installations where some cuda kernels need to be compiled, namely :
```
cd experiments/nls/mask2former/modeling/pixel_decoder/ops
sh make.sh
```

Usually this error appears when the kernels are not compiled properly. Did you face any error while compiling the kernels ? If there are issues you can try removing `experiments/nls/mask2former/modeling/pixel_decoder/ops/build` and running `make.sh` again to compile them.

**Comment by jiaxux** [comment]
Hi, thanks for the reply. I actually ran the `make.sh` without any errors (but some warning though). You could find the result in [this](https://docs.google.com/document/d/1CzUqJTNrI8i64of-gTL1kh8WsZVdjJ9-TEe9DpBblZk/edit?usp=sharing) google doc. Till now, the error is still there on my side. I also checked my basic environment setting and everything seems to work (I can process other submissions with no problems). 
I have a guess why this might happen: I am currently using a container-based setup for the evaluation; the building of the container can only take place on my local laptop, while the true inference is on a distant cluster. So, I'm curious if you think there will be any problems if the compiled kernel is not running on the same GPU as the model forward process.

**Comment by hermannsblum** [comment]
Hi! We now got the model to run when we compile it on a different workstation, but we cannot reproduce your AP on the validation set.  For the newest model (`nls_oe_30k_diversity`), we get 40% AP on the fishyscapes lostandfound validation set, you report 77%.

And we still have the kernel error: `error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device`

**Comment by hermannsblum** [comment]
I would suggest to make sure that we can execute your model correctly, please provide us with a docker image (you can upload that via the submission form) that has all software dependencies preinstalled, such that we just have to copy in our evaluation scripts based on this PR here.

**Comment by hermannsblum** [comment]
**UPDATE**
We ran it on a 3090 and that seems to work better. Your results, at least for the latest submission, are up now. I don't think we will manage any other results before the CVPR deadline, we don't have high priority for jobs on 3090s.

**Comment by NazirNayal8** [comment]
Many thanks for all your efforts in making this work, since the time deadline has become tight we decided to add these results to the supplementary, do you think we can get them before the end of next week using the 3090s ? We are particularly interested in the last submission `fishyscapes_mlp`. Your help is much appreciated.

**Comment by NazirNayal8** [comment]
Greetings again, any update on this ?

**Comment by hermannsblum** [comment]
Hi, the second round of results is online now. Is anything missing?

**Pull request closed without merging**
