### PR TITLE
An Anonymous Submission

### PR DESCRIPTION
**Pull request by Btlmd**
Hello, we'd like to measure our anonymous method in Fishysacpes Lost & Found and FS Static.

### CODE REVIEW

**Comment by hermannsblum** [comment]
Thanks for the submission. Please additionally fill in this form: https://docs.google.com/forms/d/e/1FAIpQLSdOZhG_edujhvmCp_ViQGgqkZaSDbuzmiEYlngtG1F7mNirWA/viewform

**Comment by Btlmd** [comment]
Thanks for your swift reply! I've just filled in this from. In the attachment, I've uploaded a zip file which contained all the source code as well as the checkpoint file `net.pth`.

**Comment by Btlmd** [comment]
- fix a bug: A higher anomaly score should mean that the pixel is more likely to be anomaly
- change the return value to be ndarray

**Comment by Btlmd** [comment]
By the way, we also wish to measure our model on FS Web 2022, FS Web 2021 and, if it is possible, other datasets.

**Comment by hermannsblum** [comment]
I just checked out the code, can you modify the `setup.py` such that `from inf_sing import get_score, get_net` will work? currently there are no instructions to install a package called `ing_sing`. I assume you mean the file in the root tree, but it will only work if that file is properly installed into the environment.

**Comment by Btlmd** [comment]
> 

Thanks! I'm not so sure what to do for the `setup.py`, but I think it might be an import problem due to working directory. I have appended the parent directory to `sys.path` before the import. Hopefully the code will be running this time.

**Comment by hermannsblum** [comment]
The provided `requirements.txt` does not work. Please make sure all dependencies are existing (this is just the first error of many, don't want to correct them all manually):

```
ERROR: Could not find a version that satisfies the requirement cachetools==5.0.0 (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
ERROR: No matching distribution found for cachetools==5.0.0
```

**Comment by Btlmd** [comment]
I just purged my pip cache, created a new environment and then re-installed the whole environment according to the procedures in `README.md`. In my server, the `requirements.txt` can be successfully installed. 
I was only able to reproduce this error in Python 3.6, but our code needs Python 3.8. Is Python in your environment in the right version?  :)

**Comment by hermannsblum** [comment]
That is a good point. Our standard build environment is py3.6 because of tensorflow dependencies. I will try to set up a different environment with a newer python.

**Comment by Btlmd** [comment]
I have modified the method `Anonymous_Submission` so that it will first load the Tensorflow dataset into CPU memory, reset the device, and then setup the model to perform inference. 
Note that 
```bash
pip install numba
```
is needed before running the code.
Due to lack of `fs.settings`, I haven't been able to test this method directly, but I copied the code and tested this function separately. It will solved the problem of GPU memory overflow.

**Comment by hermannsblum** [comment]
which version of numba? The newest numba does not work with the LLVM of ubuntu 20.

**Comment by Btlmd** [comment]
I tested with `numba==0.56.2` on Ubuntu 20.04 with Python 3.8.0 (and Python 3.8.13). It works and reset the GPU memory as expected.

**Comment by hermannsblum** [comment]
Just tried again with a different image of ubuntu 20.04, same error:

```
ImportError: Numba requires at least version 0.39.0 of llvmlite.

Installed version is 0.38.0.

```

I will be on holidays next week. Please find a package version or OS version that works and I can try again in 1.5 weeks.

**Comment by Btlmd** [comment]
I'm so sorry that I cannot reproduce this error. When I executed `pip install numba==0.56.2`, my `pip` automatically uninstalls `llvmlite==0.38.0` and installs `llvmlite==0.39.0` for me like this
```bash
Installing collected packages: setuptools, llvmlite, numba
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.2.0
    Uninstalling setuptools-61.2.0:
      Successfully uninstalled setuptools-61.2.0
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
    Uninstalling llvmlite-0.38.0:
      Successfully uninstalled llvmlite-0.38.0
Successfully installed llvmlite-0.39.1 numba-0.56.2 setuptools-59.8.0
```
Since `llvmlite` is just a Python package, does manually installing `llvmlite==0.39.0`  solves this issue?
```bash
pip install llvmlite==0.39.0
```
:)

**Pull request closed without merging**
