### PR TITLE
Adds our validation performance

### PR DESCRIPTION
**Pull request by jan-ackermann**
Pull Request for FishyScapes Benchmark Submission

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@icantcsharp There is a weird error when I execute the container for the test setup. I never had this before, not quite sure why this passed the validation stage but does not work in test:

```
/.singularity.d/runscript: 3: cd: can't cd to /home/user/mymask2former/anomaly_segmentation/scripts/

EXIT CODE: 2
```
any idea what could be the issue?

**Comment by jan-ackermann** [comment]
@hermannsblum I don't know why this error occurs. I have never had it locally. The only unusual thing about the file is the permissions and the group. But it indeed is very strange that it works in the validation stage.

**Comment by hermannsblum** [comment]
can you resubmit an image with less restrictive permissions on that file?
I try to emulate the test-user setup as good as possible for validation, but this setting seems to slip through. I unfortunately cannot run the container as root user on our cluster.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
it does not look like the submitted image changed

**Comment by jan-ackermann** [comment]
oh I meant the container was restricted. The code itself can be executed by anyone. I also ran it without root or sudo locally.

**Comment by hermannsblum** [comment]
no, there is a permission issue with the directory /home/user/mymask2former/anomaly_segmentation/scripts/ inside the container

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by jan-ackermann** [comment]
ok i chmod -R 777 the files, hopefully this works!

**Comment by hermannsblum** [comment]
still fails, will have to investigate on monday, sorry for that

**Comment by jan-ackermann** [comment]
Ok, thanks a lot! Have a nice weekend!

**Comment by hermannsblum** [comment]
@icantcsharp I am not able to replicate the permission issue with my github runner. However, the issue is still that `/home/user` is not permissive enough. Can you please upload a new container with more permission for the directories `/home` and  `/home/user`?

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@icantcsharp results are online. Something is wrong with your model however, even tough the validation set performance seems to match your expectation. Is the segmentation mIoU what you expected?

**Comment by jan-ackermann** [comment]
@hermannsblum yeah there definitely exists an issue. I will have a look at it. Thanks!

**Pull request closed without merging**
