### PR TITLE
Salat rev2

### PR DESCRIPTION
**Pull request by TonniaGao**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by TonniaGao** [comment]
Hi Hermann, validation is done! Could you run this container?

**Comment by hermannsblum** [comment]
yes, already on it

**Comment by hermannsblum** [comment]
but fyi: I delay subsequent results by 7 days to prevent overfitting on the test set. That means I can either give you the results of this PR as soon as I have it, and give you other results 7 days later, OR I can give you results from all your PRs together as soon as all of them are ready to run. What do you prefer?

**Comment by TonniaGao** [comment]
Sorry, I don't quite understand the second way. Does that mean if I want to see the results of all my PRs, I would have to wait for 7 days? And if I only need one PR result, I can get it now.

**Comment by hermannsblum** [comment]
It means after you see a result, if you change something in a PR, you will see the results of this PR only 7 days after getting access to a previous result.

**Comment by TonniaGao** [comment]
I understand. Could you then provide us with the results of this pull request, as well as the pull request named "PEB-rerun"? The "PEB-rerun" is merely a baseline method, and we wish to ensure fairness in our comparison by testing this model. We apologize for the inconvenience this time. We do not want to overfit the test set, and the resubmission of the container is primarily due to some output format bugs in our code.

**Comment by hermannsblum** [comment]
results are online

**Pull request closed without merging**
