### PR TITLE
valid

### PR DESCRIPTION
**Pull request by WanMotion**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by WanMotion** [comment]
Hello， @hermannsblum, an OOM error happens. Please help me to solve this. Thanks a lot.

**Comment by hermannsblum** [comment]
it worked on the cluster. Do you need the results for ICRA or is it fine if I send this on monday?

**Comment by WanMotion** [comment]
I just want to know whether the results match the data in  validation-performance.json for now. The results of the test data are not required temporarily. A new container image will be submitted latter. Thanks.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by WanMotion** [comment]
@hermannsblum , I've re-submit the container. Please deal with the OOM problem.

**Comment by hermannsblum** [comment]
@WanMotion the semantic segmentation output is not formatted correctly. Please fix that format according to the specification on our website.

The rest of the container runs correctly (I can get anomaly outputs), it is just the semantic segmentation. However, everything needs to work correctly before I can give you the results.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by WanMotion** [comment]
@hermannsblum the semantic segmentation outputs have been formatted correctly.

**Comment by hermannsblum** [comment]
results are online, thank you for your submission!

**Pull request closed without merging**
