### PR TITLE
 ADFSE - no OE

### PR DESCRIPTION
**Pull request by silviogalesso**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by silviogalesso** [comment]
I am afraid the job failed for a CUDA out-of-memory error. The model is larger this time. By the way, I wrote an overly specific model description for the last submission (cDNP-OE) but both approaches would count as cDNP.
Thank you for your work!

**Comment by hermannsblum** [comment]
thanks, most results are online already!

**Comment by silviogalesso** [comment]
Thanks! I wonder if there is any particular way you compute the Cityscapes validation performance? It doesn't match our results, although the mistake could be in our container.

**Comment by hermannsblum** [comment]
it is mean IoU on the cityscapes validation set
the exact code is here https://github.com/hermannsblum/fishyscapes/blob/feature/cluster/euler_cityscapes.py
Maybe that helps to set up the container output to match the assumed format

**Comment by silviogalesso** [comment]
Do you think it would be possible to remove the mIoU results from the leaderboard, until then?

**Comment by hermannsblum** [comment]
If you think there is an error with our code, please point towards the error. Otherwise I see nothing wrong with these results.

**Comment by silviogalesso** [comment]
I didn't mean to say that your code is wrong, rather that our is. But I understand the refusal, after all we knew that in-distribution performance was being evaluated too and we could have double checked before submitting. 
I'm only allowing myself to ask because for many methods on your leaderboard no mIoU is reported.

**Comment by hermannsblum** [comment]
I understand now your point. I hope you can also understand that the integrity of the benchmark is quite important, which is why we never removed results before.  
I still plan on converting the old submissions to the new format such that I can measure runtime and segmentation performance (as we btw did in the benchmark paper but never added online). Unfortunately, it is quite a lot of work and the next thing on the list is rather add a new Web dataset first.

**Pull request closed without merging**
