### PR TITLE
'method:ueama'

### PR DESCRIPTION
**Pull request by chensongloose**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
> your container is build for a too old version of singularity
> please resubmit a container that works with apptainer >= 1.1.5

edit: no, that was not the issue, container runs

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@chensongloose I will debug a bit the evaluation code in your PR, will let you know if there is actually a bug with the container.  
Thanks for your patience already, this is the first submission with the new system.

**Comment by hermannsblum** [comment]
@chensongloose your container does not produce any outputs. You can see the exact run-command in the log. Please make sure that it works with this command.

@4PiR2 there is the python error again, do you remember what fixed it?

**Comment by chensongloose** [comment]
Thanks for your work, I am not familiar with singularity, can you tell me what I should do to see the exact run-command.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/16/2023 23:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

@chensongloose your container does not produce any outputs. You can see the exact run-command in the log. Please make sure that it works with this command.

@4PiR2 there is the python error again, do you remember what fixed it?

**Comment by hermannsblum** [comment]
you can find the validation log here: https://github.com/hermannsblum/fishyscapes/actions/runs/4195239925/jobs/7274502516#step:3:558

**Comment by chensongloose** [comment]
Hi! 
Because I didn't set the script to run when the container started, the container does not produce any
 outputs!
         Now I have uploaded the new container to gdrive, you can download it through https://drive.google.com/file/d/16QF2Nb048tUJXXjzohd1fPlSza9GaW1k/view?usp=share_link.

| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/16/2023 23:05 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

@chensongloose your container does not produce any outputs. You can see the exact run-command in the log. Please make sure that it works with this command.

@4PiR2 there is the python error again, do you remember what fixed it?

**Comment by hermannsblum** [comment]
Can you please try again to upload it via the form? Please try the option for direct upload, not attaching a google drive resource. If it does not work, please send me a screenshot of the error.

**Comment by chensongloose** [comment]
When I tried to upload it via the form, the last block of the file could not be uploaded successfully, and the upload interface always returned the status code 403.
As you can see in the network on the right of the screenshot, the files interface keeps failing to upload files, and you can see in the content-range field is the last block of the file. My guess is that there are some Settings on your hard drive that prevent you from completing the upload or for some other reason.
Could you try to get the singularity container file through my link in gdrive for verification? Thanks for your great work!
             



| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/17/2023 17:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

Can you please try again to upload it via the form? Please try the option for direct upload, not attaching a google drive resource. If it does not work, please send me a screenshot of the error.

**Comment by hermannsblum** [comment]
Thanks for the details! If possible, can you inspect the browsers network traffic to find more details? It looks like a 403 error means that some limit is hit with your connection to google: https://developers.google.com/drive/api/guides/handle-errors#resolve_a_403_error  
Hopefully knowing the kind of limit could help resolve this for future users.

**Comment by hermannsblum** [comment]
Here are some more tips that would be helpful to go through: https://gadgetstouse.com/blog/2022/05/04/fix-google-forms-file-upload-not-working/

No worries, I am already downloading your file and will upload it on Monday, but beeing able to upload yourself will be much more convenient to debug issues.

**Comment by chensongloose** [comment]
I uploaded The file through Firefox Browser as Google Browser failed to upload, and the json file returned by the upload interface showed "The user has exceeded their Drive storage quota". It may be because your gdrive is maxed out.
You can see the details in the screenshot below.


| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/18/2023 03:08 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

Thanks for the details! If possible, can you inspect the browsers network traffic to find more details? It looks like a 403 error means that some limit is hit with your connection to google: https://developers.google.com/drive/api/guides/handle-errors#resolve_a_403_error
Hopefully knowing the kind of limit could help resolve this for future users.

**Comment by hermannsblum** [comment]
@chensongloose 
The url of your new image is broken. But until I have fixed the upload form, I added an option here where you can set a `download_url` in the `validation_performance.json` and the script will download your image from there. It just needs to be a url where `wget` can download. If you don't have a place where you can upload it to an url, I suggest e.g. zenodo.org.

In the mean time, I will further debug the form.

**Review by honglinhe — APPROVED** [review]

**Comment by chensongloose** [comment]
Hi!
Thanks for you great work! I have set a download_url in the validation_performance-json. How can I re-run the validation job?


| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/19/2023 01:09 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

@chensongloose
The url of your new image is broken. But until I have fixed the upload form, I added an option here where you can set a download_url in the validation_performance.json and the script will download your image from there. It just needs to be a url where wget can download. If you don't have a place where you can upload it to an url, I suggest e.g. zenodo.org.

In the mean time, I will further debug the form.

**Comment by hermannsblum** [comment]
The script ran, but please have a look at my comment above. It needs a url that can be downloaded by wget.
You submitted a google drive url, which does not work, because wget will download the webpage with the download button and not the image itself.

**Comment by chensongloose** [comment]
Sorry!
I tried uploading to zenodo.org. But the Internet speed of uploading image file to zenodo.org is very slow, could you please help to submit it from the link of gdrive? Thank you very much for your help!

**Comment by hermannsblum** [comment]
You have multiple options: Creating a new google account and submit through the form (I added some help to the form) or submit somewhere where the script can download directly. I don't know a way to download from google drive with a script.

**Comment by chensongloose** [comment]
Hi! Hermann,
Thanks for you help! 
I have uploaded the container file to the link that wget can get. I see that the container file has been downloaded in the job, but the verification still fails. But I can run containers very well locally. Do you have any advice on this problem?


| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/19/2023 19:10 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

You have multiple options: Creating a new google account and submit through the form (I added some help to the form) or submit somewhere where the script can download directly. I don't know a way to download from google drive with a script.

**Comment by hermannsblum** [comment]
@chensongloose There was a typo in my download function, but the container now is getting executed. Unfortunately, the pytorch version is incompatible with the device we are running the validation on. Any chance you can bump that version?

**Comment by chensongloose** [comment]
I'm currently using torch1.7.0+cuda10.2+cudnn7.6.5.
Do I need to change the torch version in the container to apply NVIDIA GeForce RTX 3080 with CUDA capability sm_86. 


| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/20/2023 17:37 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

@chensongloose There was a typo in my download function, but the container now is getting executed. Unfortunately, the pytorch version is incompatible with the device we are running the validation on. Any chance you can bump that version?

**Comment by hermannsblum** [comment]
yes, exactly

**Comment by chensongloose** [comment]
Hi! hermannsblum,
In my latest submission, CUDA is out of memory. Can I know exactly how big the memory of CUDA is?


| |
chensongloose
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/20/2023 19:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] 'method:ueama' (PR #40) |

yes, exactly

**Comment by hermannsblum** [comment]
you can find the total memory of the GPU in the error log

I can try to find a better GPU for our validation node, but is there a chance it will work with this one?

**Comment by chensongloose** [comment]
@hermannsblum That's great! Thank you so much for your help. Replace the better GPU is able to run validation job.

**Comment by chensongloose** [comment]
@hermannsblum To rerun the validation node, should I resubmit in this PR?

**Comment by chensongloose** [comment]
Hi @hermannsblum ,
I tried to run validation jobs using less gpu space. But this way need to create folders to hold intermediate results. Could you please add "-- writable" to the command that runs the container and run it using sudo? Thanks for you help!

**Comment by chensongloose** [comment]
Hi @hermannsblum,
In my latest commit( https://github.com/hermannsblum/fishyscapes/actions/runs/4291535705/jobs/7476842328) the script in container finished executing, but a new error was shown in eval. If possible, could you tell me how to solve it?

**Comment by chensongloose** [comment]
@hermannsblum  There is a bug in eval. Can you fix it?

**Comment by chensongloose** [comment]
@hermannsblum Thanks for your help! Because my method generates some intermediate results, which cannot be guaranteed to be exactly the same each time, there is a 0.5％ error in ap and fpr each time, and the verified results are in line with expectations. Can you run the test sets in my method?

**Comment by hermannsblum** [comment]
@chensongloose good, will do tomorrow. If you want you can update this here in the mean time with your original model. I moved the runner today to a 12gb gpu.

(I will report runtime per frame of the methods in a soon-to-be-added column and assume that this will make quite a difference.)

**Comment by hermannsblum** [comment]
When executing on our cluster, your container still has errors:
```
>>> None $ singularity run --nv --writable-tmpfs --bind /scratch/tmp.11073001.blumh/outputs:/output,/scratch/tmp.11073001.blumh/inputs:/input /scratch/tmp.11073001.blumh/image.simg

Traceback (most recent call last):

  File "data_preparation_fishyscapes/data_preprocess.py", line 34, in <module>

    net, _ = restore_snapshot(net, optimizer=None, snapshot=opt.snapshot, restore_optimizer_bool=False)

  File "./image_segmentation/optimizer.py", line 69, in restore_snapshot

    checkpoint = torch.load(snapshot, map_location=torch.device('cpu'))

  File "/opt/conda/envs/px/lib/python3.7/site-packages/torch/serialization.py", line 579, in load

    with _open_file_like(f, 'rb') as opened_file:

  File "/opt/conda/envs/px/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like

    return _open_file(name_or_buffer, mode)

  File "/opt/conda/envs/px/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__

    super(_open_file, self).__init__(open(name, mode))

PermissionError: [Errno 13] Permission denied: 'models/image-segmentation/cityscapes_best.pth'

EXIT CODE: 1

Traceback (most recent call last):

  File "euler.py", line 42, in main

    run(cmd)

  File "/cluster/home/blumh/fishyscapes/new_system/fishyscapes/utils.py", line 29, in run

    assert rc == 0

AssertionError



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "euler.py", line 71, in <module>

    main()

  File "euler.py", line 45, in main

    raise UserWarning("Execution of submitted container failed. Please take a look at the logs and resubmit a new container.")

UserWarning: Execution of submitted container failed. Please take a look at the logs and resubmit a new container.
```

**Comment by chensongloose** [comment]
The container ran successfully during validation without this problem.Have you ever encountered this problem before?

**Comment by hermannsblum** [comment]
No, this is a problem I have never encountered before with any other container than yours. It looks like an internal permission problem inside the container.

**Comment by chensongloose** [comment]
If possible, can you run the test sets on the cluster where the validation is working?

**Comment by hermannsblum** [comment]
Unfortunately, that is not possible. I will try to investigate how to best replicate the cluster setup on the CI server, but our large GPU cluster is not directly connected to the internet and I also do not want to execute arbitrary code automatically.

**Comment by hermannsblum** [comment]
@4PiR2 I remember you encountered a permission problem once, is this related?

**Comment by chensongloose** [comment]
Maybe try using sudo to execute the container, but I don't know if that would be useful.

**Comment by chensongloose** [comment]
Hi @hermannsblum ,Will my submitted container now run on your cluster?

**Comment by hermannsblum** [comment]
As my message from yesterday shows, there is a permission issue with a file inside the container that you submitted. Once you fix that, I can try running it again.

**Comment by hermannsblum** [comment]
@chensongloose one idea to look into: Are you defining a run-script in singularity or in docker and just translating to singularity? We had some permission issues before if the runscript is not defined in singularity.

The second thing that I am currently looking into is if the user inside the container changes on our cluster, I will let you know.

**Comment by chensongloose** [comment]
Thanks @hermannsblum !My latest submitted container has all file permissions set to readable. Can you try running the container on the test cluster?
I'm going to try to define runscript in singularity next.

**Comment by hermannsblum** [comment]
@chensongloose We found the problem. On our cluster, containers are not executed as root but as user 'blumh'. I adapted the validation job accordingly. If this goes through, hopefully I have numbers for you soon.

**Comment by chensongloose** [comment]
If I understand correctly, and singularity can be started with root on the validation cluster, can you do the same on the test cluster?

**Comment by hermannsblum** [comment]
@chensongloose Unfortunately there is another error when running your container on our big cluster: Even with --writable-tmpfs it writes too much data inside the container and our cluster with more strict security settings does not allow that.

The best option is probably to just remove the read-in-and-out of the intermediate stages again and I just run this on a large enough GPU there. Since I moved the evaluation node also to a larger GPU this should now all work.

**Comment by chensongloose** [comment]
I have locally tested a GPU that requires 24gb of memory to run my container without intermediate stages. Is it possible to modify the security settings of the large cluster to run our container.

**Comment by hermannsblum** [comment]
No, I don't have permissions on the large cluster to do that and I don't have 24gb GPUs anywhere else.

**Comment by chensongloose** [comment]
Thanks for your work. Is there any other way to make our container run on the test set? Because we really did a lot of work and needed this result.

**Comment by hermannsblum** [comment]
As I said: The best option is probably to just remove the read-in-and-out of the intermediate stages again. Even if this may OOM on the validation server, we now know that in theory the container worked and I can run this on the cluster on a 24gb GPU. However, please make sure that the container does not run into permission issues (currently I think there are none).

I understand that you had to put in a lot of effort. It also looks to me like this is the first time that you are working with containers. Please also understand that I probably gave you more than 3 full working days of support time and continue to support. In the meantime, 2 other submissions were processed with much fewer issues and they therefore already have their results.

**Comment by chensongloose** [comment]
Sorry for taking up so much of your time. Because I was working with singularity for the first time, I had so many problems with my proposal. Thanks  for your support!

**Comment by chensongloose** [comment]
@hermannsblum Can you help resolve conflicts

**Comment by chensongloose** [comment]
@hermannsblum The latest submission failed. This job failure may be caused by using an out of date self-hosted runner. You are currently using runner version 2.301.1. Please update to the latest version 2.302.1. Can you fix it? Thanks!

**Comment by hermannsblum** [comment]
the job fails because you try to establish a network connection and download vgg parameters. We cannot allow network connections since these may leak the test set.
Just make sure in your build script that you already invoke the parameter loading before uploading the container.

**Comment by hermannsblum** [comment]
looks already running good enough, I am starting this on the cluster 👍

**Comment by hermannsblum** [comment]
@chensongloose it looks like your method does not produce semantic segmentation maps?

**Comment by chensongloose** [comment]
You can see in the screenshot below that the semantic segmentation map is saved.
image

**Comment by hermannsblum** [comment]
and you pushed a new model, should I rerun with the newest or report results of [35bdfca](https://github.com/hermannsblum/fishyscapes/pull/40/commits/35bdfca95a5a05fcb522355204f98327a7d3ae22) on the website?

**Comment by chensongloose** [comment]
These two submissions are a model. You can report results of [35bdfca](https://github.com/hermannsblum/fishyscapes/pull/40/commits/35bdfca95a5a05fcb522355204f98327a7d3ae22) on the website

**Comment by hermannsblum** [comment]
OK, a first result is online! The other results will be added in the next hours.

**Comment by chensongloose** [comment]
Thanks for your great work!

**Comment by hermannsblum** [comment]
Thanks for your great patience! FYI, if you want to submit another version of the model, please open a second PR.

**Review by hermannsblum — APPROVED** [review]

**Comment by hermannsblum** [comment]
all results are online

**Pull request merged**
