### PR TITLE
ADFSE - ViT-L + OE

### PR DESCRIPTION
**Pull request by silviogalesso**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@silviogalesso should this OOM even with a 12GB gpu?

**Comment by silviogalesso** [comment]
It should have the exact same requirement as the last submission.

**Comment by hermannsblum** [comment]
OK, just asking because I moved the validation runner to a larger GPU, but still seems insufficient for your submission.
Anyways, results are online. Thanks for the submission!

**Pull request closed without merging**
