### PR TITLE
New Anomaly Segmentation Method

### PR DESCRIPTION
**Pull request by shyam671**
Please, evaluate the method.

### CODE REVIEW

**Comment by hermannsblum** [comment]
Something is not working correctly for importing things from `mask2former`:

```
/Mask2Former/fishyscapes/ood_func
['/Mask2Former/fishyscapes/ood_func', '/Mask2Former/fishyscapes/ood_func', '/Mask2Former/fishyscapes/ood_func/..', '/Mask2Former/fishyscapes/experiments', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/Mask2Former/fishyscapes', '/usr/local/lib/python3.8/dist-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg', '/usr/lib/python3/dist-packages']
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-6zivh6y8 because the default path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "fishyscapes/experiments/fishyscapes.py", line 4, in <module>
    from ood_func import ood_func
  File "/Mask2Former/fishyscapes/experiments/ood_func.py", line 38, in <module>
    from mask2former import add_maskformer2_config, SemanticSegmentorWithTTA
ModuleNotFoundError: No module named 'mask2former'
```

I think the easiest would be to supply a `setup.py` that installs your `mask2former` module.

**Comment by shyam671** [comment]
Dear Hermann,

I have fixed the problem and sent you the updated zip file.

Thank you for your patience

**Comment by hermannsblum** [comment]
fyi here are already some submission instructions for the new system: https://fishyscapes.com/submission

**Comment by hermannsblum** [comment]
The new submission system is now live. Please make a new pull-request following the website instructions. You can contact me any time if you need help.

**Pull request closed without merging**
