### PR TITLE
DA(rev2)

### PR DESCRIPTION
**Pull request by chensongloose**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by chensongloose** [comment]
@hermannsblum ,Can you run the container on your cluster?

**Comment by hermannsblum** [comment]
yes I will. To prevent overfitting on the testset, I always wait 1 week until releasing results of a revised submission, so next Thursday.

**Comment by chensongloose** [comment]
@hermannsblum Please run the latest committed container on your cluster, the previous version does not need to run . Thanks!

**Comment by chensongloose** [comment]
Hi @hermannsblum.The last committed container did not run out of GPU memory. The new submissions seem to be experiencing this problem, but there are no major changes between them.

**Comment by hermannsblum** [comment]
the change is on my end unfortunately. Somebody broke the nvidia drivers on the standard CI server and I had to temporarily move to a machine with smaller GPU. I will just run this now on the cluster without validation to get you the results.

**Comment by hermannsblum** [comment]
@chensongloose the container does not output the segmentation map in the correct format, please check and resubmit.

**Comment by chensongloose** [comment]
I'm terribly sorry. I resubmitted the container.

**Comment by chensongloose** [comment]
Hi, @hermannsblum .Can we choose which period to run this data set of FS Web, so that we can compare it with other methods?

**Comment by chensongloose** [comment]
Please help to run the newly submitted container on the cluster, thank you very much! @hermannsblum

**Comment by chensongloose** [comment]
The graduation thesis is about to be submitted and waiting for the result. Please help run the latest committed container on the cluster.Thanks for your help! @hermannsblum

**Comment by hermannsblum** [comment]
Sorry, we have a big holiday weekend here (Easter). Results are online now.

**Pull request closed without merging**
