### PR TITLE
New anonymous submission

### PR DESCRIPTION
**Pull request by matejgrcic**

### CODE REVIEW

**Comment by hermannsblum** [comment]
@matejgrcic Please allow me pushing to this branch in your fork such that I can upload the fixes I had to deploy

**Comment by matejgrcic** [comment]
@hermannsblum I've added you as a collaborator to the forked repo.

**Comment by matejgrcic** [comment]
submission for DenseHybrid without auxiliary dataset (ood_ratio method)

**Comment by hermannsblum** [comment]
thanks for the addition, numbers are online as revision 4. Let me know if I should change the name to something else. Happy New Year :)

**Comment by matejgrcic** [comment]
Thanks a lot, Hermann. Happy New Year!

**Pull request closed without merging**
