### PR TITLE
M2A (rev2)

### PR DESCRIPTION
**Pull request by shyam671**
Please, find a revised version of M2A to be grouped as M2A (rev 2) in the website table.

### CODE REVIEW

**Comment by shyam671** [comment]
Hi @hermannsblum ,
Could you please evaluate the revised submission?

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@shyam671 very sorry about this, something on the FS Static job failed and I need to rerun. Since the method is so slow, that will take another 48 hours. The FS Lost & Found results are online tough.

**Comment by shyam671** [comment]
Thanks @hermannsblum. No worries 🙂. Please take your time.

**Comment by hermannsblum** [comment]
all results are online

**Review by hermannsblum — APPROVED** [review]

**Comment by shyam671** [comment]
Thanks @hermannsblum

**Pull request merged**
