### PR TITLE
Simplified Detector

### PR DESCRIPTION
**Pull request by mbisan**
This is a simplified version of the DenseHybrid model without an OOD-head.

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
Thanks! Per our policy, you will get the results only in 6 days.

**Comment by hermannsblum** [comment]
results are online. Please let me know how I should name the variants.

**Comment by mbisan** [comment]
Hi, naming is ok as it is.

Thank you!

**Pull request closed without merging**
