### PR TITLE
M2A

### PR DESCRIPTION
**Pull request by shyam671**
Please, find the evaluate the new requested method.

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@shyam671 as you can see in the evaluation logs, your container does not produce any outputs.

**Comment by shyam671** [comment]
Please, evaluate the revised submitted container.

**Comment by hermannsblum** [comment]
@shyam671 just for me to check, because I thought I enabled this: If you click on validation details, is there a button to rerun yourself?

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by shyam671** [comment]
@hermannsblum If I correctly understood your comment, I didn't find any button to rerun the evaluation automatically starts and gives us the output.

**Comment by hermannsblum** [comment]
@shyam671 so just to be clear, you do not see the button "re-run all jobs" on the top right in this screenshot?

image

**Comment by shyam671** [comment]
No it is not showing for me
Screenshot 2023-02-21 at 8 55 03 AM

**Comment by hermannsblum** [comment]
OK, thanks for checking. fyi, the validation looks good and your method is currently running on the cluster to evaluate on the testset. I will post here once the results are online. Can you already let me know the answers to the other questions in the form that you could not submit?

**Comment by shyam671** [comment]
Thanks @hermannsblum. The other answers are:
 Trains on OoD data: yes, retrain the segmentation network: No. , Method Name: M2A

**Comment by hermannsblum** [comment]
@shyam671 first results are online, but FS Static took more than 24h to complete and was cancelled. I restarted it with a 48h limit, it will take a while until the result is there

**Comment by shyam671** [comment]
Hi @hermannsblum ,
Did we manage to get results on FS static ? Also, if I have an improved model, should I resubmit in this PR or make a new PR ?

**Comment by hermannsblum** [comment]
All results are online now. For a new variant, please submit a new pull-request and mention how it should be grouped in the website table.

**Pull request closed without merging**
