### PR TITLE
Update fishyscapes.py

### PR DESCRIPTION
**Pull request by ShashwatNaidu**
Hello,
The following pull request is for testing our model on fishyscapes dataset. This model is based on the resynthesis model proposed by Giandbt.
For this code to work the following repo must be cloned : https://github.com/ShashwatNaidu/synboost.git

The weights for the models can be found here: https://drive.google.com/file/d/1qRBTy_1lUFV1M2-J2tDWp4xGB0AlY_Ke/view?usp=sharing. These weights need to be unzipped inside the cloned repository.

### CODE REVIEW

**Comment by BoySun045** [comment]
Hi, 
Thanks for the submission and the instruction. 

There are several parts you need to modify to cooperate with the benchmark testing process:
   - Please make a setup.py for your repo, in order to make it an installable package. 
   - Please check the import path in your fishyscapes.py and test_fishy_torch.py, for the first one there are some pkg imported using a relative path, and for the second one pkgs such as "network, optimizer, datasets" are not found during building the singularity file. 

We have modified these for you and continue to the next steps, but please notice these and it is also recommended to change it in your submissions as well. Thanks!

**Comment by ShashwatNaidu** [comment]
Thank you for your reply
Sorry for the inconvenience. Our work is actually very similar to Pixel-wise Anomaly Detection for Complex Outdoors Scenes with very small modifications.  Now we have directly copied the repo of the previous paper and made changes in it. We believe this should work (https://github.com/ShashwatNaidu/Synboost_fishyscapes.git) . I don't think even the commit we made to update fishyscapes.py is required as the re-synthesis model function is already present in it. 

New link : https://github.com/ShashwatNaidu/Synboost_fishyscapes.git. 
The models.zip file is same as before (https://drive.google.com/file/d/1qRBTy_1lUFV1M2-J2tDWp4xGB0AlY_Ke/view?usp=sharing). This models zip file needs to be unzipped inside the driving uncertainty folder.

We regret any inconvenience caused to you, hope this works fine.

**Comment by ShashwatNaidu** [comment]
Hello, 
This is revision 2 of the same model which we had submittted.  We have submitted our revised model in the google form too. The instructions are more or less same, this github repo needs to be cloned (https://github.com/ShashwatNaidu/Synboost_fishyscapes.git) and this zip file (https://drive.google.com/file/d/1FX4_df0SkmhnU_1ymTRDKHuueXlV4W4X/view?usp=sharing) needs to be unzipped inside the driving uncertainty folder. The function resynthesis model present under fishyscapes.py needs to be run for this model to work.

**Comment by hermannsblum** [comment]
done

**Pull request closed without merging**
