### PR TITLE
DGA

### PR DESCRIPTION
**Pull request by chensongloose**

### CODE REVIEW

**Comment by chensongloose** [comment]
@hermannsblum The validation of my newly submitted container has been completed, please run it on your cluster. Thanks!
In addition, the container output semantic segmentation file suffix is _semantically.npy.

**Comment by hermannsblum** [comment]
please change the semantic output back to _segmentation.npy  You cannot just change our order evaluation function to make the validation happy. The validation is here to make sure your submitted model works with our setup.

**Comment by hermannsblum** [comment]
OK, results are in. Can you let me know the answers to the form questions or submit the form? Then I can publish the results to the website.

**Comment by chensongloose** [comment]
Thanks! Due to container file size issues, I submitted an image to bypass form validation.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
Thanks! Everything is online now.

**Pull request closed without merging**
