### PR TITLE
adds new method: anomalytj

### PR DESCRIPTION
**Pull request by yuanpengtu**
adds new method: anomalytj

### CODE REVIEW

**Comment by hermannsblum** [comment]
this PR does not match your submitted zip file (the PR adds real_time_sigmoid, the zip file anomalytj). Which should I use?

**Comment by yuanpengtu** [comment]
> this PR does not match your submitted zip file (the PR adds real_time_sigmoid, the zip file anomalytj). Which should I use?

Sorry, it seems that I make some mistakes in the PR. Please use the anomalytj in the submitted zip file.

**Comment by hermannsblum** [comment]
Please provide better instructions for package installations. The README is not in English, so I cannot read it. This is the current error I get when trying to run your evaluation:
```
Traceback (most recent calls WITHOUT Sacred internals):
  File "experiments/fishyscapes.py", line 257, in anomalytj
    from core.inference import AnomalyDetect
  File "/fishyscapes/anomalytj/core/__init__.py", line 1, in <module>
    import core.modeling.codec as codec
  File "/fishyscapes/anomalytj/core/modeling/codec.py", line 11, in <module>
    from mmseg.core import add_prefix
  File "/fishyscapes/anomalytj/mmseg/__init__.py", line 4, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
```

**Comment by yuanpengtu** [comment]
> README is not in English
I have re-submitted the file with English README. Please refer to the updated version.

**Comment by hermannsblum** [comment]
Thanks for updating this! Unfortunately, `mmcv` does not compile in our default environment. Can you suggest a docker image that I could use that already has mmcv and whatever version of pytorch that you require? I will then try to build our evaluation setup on top of that.

**Comment by yuanpengtu** [comment]
> Thanks for updating this! Unfortunately, `mmcv` does not compile in our default environment. Can you suggest a docker image that I could use that already has mmcv and whatever version of pytorch that you require? I will then try to build our evaluation setup on top of that.

Sorry, it seems that the complete docker image is too big (around 16.3G) to share. The Pytorch version we use is 1.9.0 and cuda 11.1.

**Comment by yuanpengtu** [comment]
> > Thanks for updating this! Unfortunately, `mmcv` does not compile in our default environment. Can you suggest a docker image that I could use that already has mmcv and whatever version of pytorch that you require? I will then try to build our evaluation setup on top of that.
> 
> Sorry, it seems that the complete docker image is too big (around 16.3G) to share. The Pytorch version we use is 1.9.0 and cuda 11.1. Moreover, you can also refer to https://mmcv.readthedocs.io/en/latest/get_started/build.html to build mmcv from source code.

**Comment by yuanpengtu** [comment]
Hi, is the code being run successfully now?

**Comment by hermannsblum** [comment]
done

**Comment by hermannsblum** [comment]
in line for another checkpoint

**Comment by hermannsblum** [comment]
done

**Pull request closed without merging**
