### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by stdrr**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
thanks for the submission! It looks like the validation runner is stuck somewhere, I will try to fix it until tomorrow

**Comment by hermannsblum** [comment]
@stdrr the validation job fails because the container cuda/pytorch combination is too new. Can you resubmit a container that is compatible with older cuda?

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
@stdrr I really don't understand what you are trying to do, but it is way easier to keep one PR open and update the image through the google form. If you want to trigger retests, just change the json file and add some spaces somewhere, or ping me here with a message. If you re-open PRs all the time, I can also not test your image on our cluster (bypassing the validation), because your new PR does not have an image uploaded yet...

**Comment by stdrr** [comment]
@hermannsblum I apologize if I misunderstood the submission instructions. I was trying to restart the job to run the container as stated in (3) and I expected the job to be triggered again after every image update. Since it was not, I thought I had to open a new PR.

Regarding the new PR, I did upload an image, but it is not loaded correctly, maybe there are some problems with the file on GDrive itself. I'll check the file and follow your instructions.

Thank you, I apologize again for the inconvenience.

**Pull request closed without merging**
