### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by stdrr**

### CODE REVIEW

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by stdrr** [comment]
Dear @hermannsblum, I'm sorry if I disturb you.

My container keeps failing due to the shared memory running out. I have tried to set the number of workers to 0, but this doesn't solve the issue. May I ask what the maximum system limit is to avoid crashes?

Thank you.

**Comment by hermannsblum** [comment]
Hi @stdrr I saw the error. I don't know exactly why the validation fails, but I started yesterday to directly run your method on the benchmark. Unfortunately a few weeks ago our Uni switched the OS of our GPU cluster and something is wrong with the singulariry executable there. I filed an issue and am waiting for their response. I will update you here if the container works on our larger machines.

**Comment by stdrr** [comment]
Hi @hermannsblum, thank you for your prompt answer and your help. I'll keep trying to reduce the resources required by my container.

**Comment by stdrr** [comment]
Hi @hermannsblum, is there any news about the evaluation environment and the container? 
Thank you.

**Comment by hermannsblum** [comment]
Hi @stdrr 
They were not yet able to fix the issue, but in an unrelated project I was able to get my containers work when I rebuilt them on a ubuntu22.04 host (newer probably also works).
Is this something you could do?

**Comment by stdrr** [comment]
Thanks for your answer, I think so, I'll try to rebuild the container on a host with that OS version.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by hermannsblum** [comment]
A new container image was submitted.

**Comment by stdrr** [comment]
Hi @hermannsblum, 
I submitted a container built on a machine with Ubuntu 22.04, as you suggested. 
Please let me know if anything else is required.
Thank you

**Comment by stdrr** [comment]
Dear @hermannsblum,

I see that the check keeps failing due to insufficient shared memory for the data loader worker. I spawn only one process (`num_workers=0` in Pytorch's data loader), and that requires 0.28GB on my system. Is 0.28GB still too much?

Thank you,
Stefano

**Comment by hermannsblum** [comment]
@stdrr I finally managed to fix the problems on my side. I don't think the validation runner is meaningful, I can now finally run your container on the cluster anyways.  
However, there is a problem. You seem to use slurm internally in the container? That looks like it is interfering with the slurm on our cluster:

```
[rank: 0] Seed set to 0
Saving to ../output/best_cfg_no_scale/
Loading checkpoint from ../ckpts/submission.ckpt
Loading checkpoint from ../ckpts/submission.ckpt
Traceback (most recent call last):
  File "/ANORM/test.py", line 96, in <module>
    main()
  File "/ANORM/test.py", line 81, in main
    trainer = pl.Trainer(
  File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 395, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 149, in __init__
    self.cluster_environment: ClusterEnvironment = self._choose_and_init_cluster_environment()
  File "/opt/conda/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 409, in _choose_and_init_cluster_environment
    return env_type()
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py", line 54, in __init__
    self._validate_srun_variables()
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py", line 221, in _validate_srun_variables
    raise RuntimeError(
RuntimeError: You set `--ntasks=4` in your SLURM bash script, but this variable is not supported. HINT: Use `--ntasks-per-node=4` instead.
```

**Comment by stdrr** [comment]
@hermannsblum Thank you for your answer. My code uses Lightning, which, by default, reads the SLURM configuration variables and expects certain parameters (e.g., `--ntasks-per-node` instead of `--ntasks`). I patched the code to prevent Lightning from accessing the SLURM configuration. I tested it on a system managed by SLURM, and it no longer throws that error.

Thank you.
Stefano

**Comment by hermannsblum** [comment]
@stdrr  Thanks a lot for your amazing patience. Finally, your first results are online and the rest will come soon. One thing that I am not sure about is that you say you do not retrain the segmentation model, but actually your cityscapes val score is very low?

**Comment by stdrr** [comment]
@hermannsblum Thank you very much for your availability! I didn't expect such a low mIoU - the model should reach ~80.80, which is the performance of the pre-trained version. Probably, I'm not properly saving the segmentation masks. I'll double-check and let you know.

Thank you,
Stefano

**Comment by hermannsblum** [comment]
all results are online now

**Pull request closed without merging**
